#5600 rpm???
axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.75
scale_linear_turbo: 1.5833627 

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.915238555 #0.3925 
scale_angular_turbo: 1.83047711 #0.785 

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button
