######################
##    CAN Config    ##
######################

# Interface
/receiver_interface:     "can0"
/transmitter_interface:  "can0"

# Topics
/receiver_list:          ["/switchesTurntableFlags", "/switchesForearmFlags", "switchesShoulderFlags", "/science", "/current_sensors", "/thermistors"]
