######################
##    CAN Config    ##
######################

# Interface
/receiver_interface:     "vcan0"
/transmitter_interface:  "vcan0"

# Topics
/receiver_list:          ["/switchesWristFlags", "/switchesForearmFlags", "switchesShoulderFlags", "/science", "/current_sensors", "/thermistors"]
