######################
##    CAN Config    ##
######################

# Interface
/receiver_interface:     "can0"
/transmitter_interface:  "can0"

# Topics
/receiver_list:          ["/limit_switches",  "/i2c", "/current_sensors", "/thermistors"]
