######################
##    CAN Config    ##
######################

# Interface
/receiver_interface:     "can0"
/transmitter_interface:  "can0"

# Topics
/receiver_list:          ["/switchesWristFlags", "/switchesForearmFlags", "switchesShoulderFlags", "/science", "/current_sensors", "/thermistors"]
