// Generated by gencpp from file python_service_test/PanoServiceRequest.msg
// DO NOT EDIT!


#ifndef PYTHON_SERVICE_TEST_MESSAGE_PANOSERVICEREQUEST_H
#define PYTHON_SERVICE_TEST_MESSAGE_PANOSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace python_service_test
{
template <class ContainerAllocator>
struct PanoServiceRequest_
{
  typedef PanoServiceRequest_<ContainerAllocator> Type;

  PanoServiceRequest_()
    : go(0)  {
    }
  PanoServiceRequest_(const ContainerAllocator& _alloc)
    : go(0)  {
  (void)_alloc;
    }



   typedef int32_t _go_type;
  _go_type go;




  typedef boost::shared_ptr< ::python_service_test::PanoServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::python_service_test::PanoServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PanoServiceRequest_

typedef ::python_service_test::PanoServiceRequest_<std::allocator<void> > PanoServiceRequest;

typedef boost::shared_ptr< ::python_service_test::PanoServiceRequest > PanoServiceRequestPtr;
typedef boost::shared_ptr< ::python_service_test::PanoServiceRequest const> PanoServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::python_service_test::PanoServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace python_service_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::python_service_test::PanoServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::python_service_test::PanoServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::python_service_test::PanoServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3088de2ecd8419c46ce22de2b2ca304a";
  }

  static const char* value(const ::python_service_test::PanoServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3088de2ecd8419c4ULL;
  static const uint64_t static_value2 = 0x6ce22de2b2ca304aULL;
};

template<class ContainerAllocator>
struct DataType< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "python_service_test/PanoServiceRequest";
  }

  static const char* value(const ::python_service_test::PanoServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 go\n\
";
  }

  static const char* value(const ::python_service_test::PanoServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.go);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PanoServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::python_service_test::PanoServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::python_service_test::PanoServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "go: ";
    Printer<int32_t>::stream(s, indent + "  ", v.go);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYTHON_SERVICE_TEST_MESSAGE_PANOSERVICEREQUEST_H
