// Generated by gencpp from file python_service_test/PanoService.msg
// DO NOT EDIT!


#ifndef PYTHON_SERVICE_TEST_MESSAGE_PANOSERVICE_H
#define PYTHON_SERVICE_TEST_MESSAGE_PANOSERVICE_H

#include <ros/service_traits.h>


#include <python_service_test/PanoServiceRequest.h>
#include <python_service_test/PanoServiceResponse.h>


namespace python_service_test
{

struct PanoService
{

typedef PanoServiceRequest Request;
typedef PanoServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PanoService
} // namespace python_service_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::python_service_test::PanoService > {
  static const char* value()
  {
    return "b5eb47b68f24cd3aaa45ca1005960292";
  }

  static const char* value(const ::python_service_test::PanoService&) { return value(); }
};

template<>
struct DataType< ::python_service_test::PanoService > {
  static const char* value()
  {
    return "python_service_test/PanoService";
  }

  static const char* value(const ::python_service_test::PanoService&) { return value(); }
};


// service_traits::MD5Sum< ::python_service_test::PanoServiceRequest> should match 
// service_traits::MD5Sum< ::python_service_test::PanoService > 
template<>
struct MD5Sum< ::python_service_test::PanoServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::python_service_test::PanoService >::value();
  }
  static const char* value(const ::python_service_test::PanoServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::python_service_test::PanoServiceRequest> should match 
// service_traits::DataType< ::python_service_test::PanoService > 
template<>
struct DataType< ::python_service_test::PanoServiceRequest>
{
  static const char* value()
  {
    return DataType< ::python_service_test::PanoService >::value();
  }
  static const char* value(const ::python_service_test::PanoServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::python_service_test::PanoServiceResponse> should match 
// service_traits::MD5Sum< ::python_service_test::PanoService > 
template<>
struct MD5Sum< ::python_service_test::PanoServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::python_service_test::PanoService >::value();
  }
  static const char* value(const ::python_service_test::PanoServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::python_service_test::PanoServiceResponse> should match 
// service_traits::DataType< ::python_service_test::PanoService > 
template<>
struct DataType< ::python_service_test::PanoServiceResponse>
{
  static const char* value()
  {
    return DataType< ::python_service_test::PanoService >::value();
  }
  static const char* value(const ::python_service_test::PanoServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PYTHON_SERVICE_TEST_MESSAGE_PANOSERVICE_H
