axis_linear: 1  # Left thumb stick vertical
scale_linear: 1.0 
scale_linear_turbo: 2.0 

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 1.0 #0.3925 
scale_angular_turbo: 2.0 #0.785 

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button
