global_frame: odom
rolling_window: true
track_unknown_space: true

width: 2200
height: 2200
resolution: 0.5

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}