global_frame: odom
rolling_window: true

width: 10
height: 10
resolution: 0.05

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}